name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: prepare
        id: prepare
        env:
          BRUTPATHS: |
            {"docker":[],"helm":[],"helmfile":[],"packer":[],"rego":[],"terraform":[".cloud/terraform",".cloud/terraform/modules/xxxx",".cloud/terraform/blsbls-staging"],"terraformWithWorkspace":[{"path":".cloud/terraform","workspace":"xx-prod"},{"path":".cloud/terraform","workspace":"xx-staging"},{"path":".cloud/terraform/modules/proxy_api_v2","workspace":"default"},{"path":".cloud/terraform/blsbls-staging","workspace":"default"}]}

          BRUTISP: |
            [
              {
                  "name": "bloblo",
                  "workspace": "xx-staging",
                  "role": "bloblo-backend-deploy-lambda",
                  "runner": "bloblo-backend-lambda"
              },
              {
                  "name": "bloblo",
                  "workspace": "xx-prod",
                  "role": "bloblo-backend-deploy-lambda",
                  "runner": "bloblo-backend-lambda"
              },
              {
                  "name": "blsbls",
                  "workspace": "default",
                  "role": "blsbls-backend-deploy-lambda",
                  "runner": "blsbls-backend-lambda"
              }
            ]
        run: |
          echo "BRUTPATHS=${BRUTPATHS}" >> $GITHUB_OUTPUT

          BISP=$(echo "${BRUTISP}" | jq -c .)
          echo "BRUTISP=${BISP}" >> $GITHUB_OUTPUT
      - name: debug
        run: |
          echo "${{ steps.prepare.outputs.BRUTPATHS }}"
          echo "${{ steps.prepare.outputs.BRUTISP }}"
      - name: Build matrix
        uses: actions/github-script@v6
        id: build-matrix
        env:
          PATHS: ${{ join(fromJson(steps.prepare.outputs.BRUTPATHS).terraform) }}
          ISP: ${{ join(steps.prepare.outputs.BRUTISP) }}
        with:
          script: |
            const script = require('./.github/scripts/build-matrix-isp.js')
            script({context, core});
      - name: debug
        run: echo "${{ steps.build-matrix.outputs.result }}"
